### ISSUE TITLE
How to work that?

### ISSUE THREAD

**Issue by Jokerjokerjoke** [ri3tykity/rxce-automation#1]
How can i do that code tell step by step please🙏

**Comment by Jokerjokerjoke** [comment]
Is that rxce hacking code?

**Comment by ri3tykity** [comment]
This is not a hacking code... It is a selenium automation tool which run RXCE in chrome automatically.
Then login to your account, you need to provide your username/password in program.cs file.
There are 3 kind of pattern detection: Low/Med/High
Based on current pattern it will choose a color and then automatic buy 1 point of that color from screen.
Thats all. 
I am working on it to enhance/add more feature...

**Comment by Jokerjokerjoke** [comment]
You mean automatic color selection

**Comment by Jokerjokerjoke** [comment]
How to use that

**Comment by Jokerjokerjoke** [comment]
Get any loss?

**Comment by ri3tykity** [comment]
> You mean automatic color selection

Yes.

**Comment by ri3tykity** [comment]
> How to use that

You can clone this project and run in your own laptop/desktop. Or soon I will update this project with EXE build that can directly run. Yes there was some loss during the testing phase. I have removed that bug.

**Comment by Jokerjokerjoke** [comment]
How much loss

**Comment by ri3tykity** [comment]
> How much loss

Around Rs. 120....
You must have some amount in your RXCE account while using this application.

**Comment by Jokerjokerjoke** [comment]
How to use can you tell me step by step

**Comment by Jokerjokerjoke** [comment]
User name was mobile no.?
