### ISSUE TITLE
Minimum funds to run this program

### ISSUE THREAD

**Issue by KILL-COD3R** [ri3tykity/rxce-automation#2]
What is the minimum funds should we have in rxce while running this program?

**Comment by ri3tykity** [comment]
This is our first version of code. It will run even Rs.10 available in your account. But preferably Rs. 100 would be nice to have.

**Comment by Jokerjokerjoke** [comment]
Username was mobile no. Or not?

**Comment by Jokerjokerjoke** [comment]
How to work this please tell step by step

**Comment by Kranthi8886** [comment]
Bro

> This is our first version of code. It will run even Rs.10 available in your account. But preferably Rs. 100 would be nice to have.

Bro how can i run code bro help me
